server:
  port: 8090
spring:
  application:
    name: Loan-API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jbdc:mysql://localhost:3306/loan_api?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

