server:
  port: 8761
spring:
  application:
    name: naming-server
eureka:
  client:
    register-with-eureka: false # REMOVE IN PRODUCTION PROFILE?
    fetch-registry: false # REMOVE IN PRODUCTION PROFILE?
