server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LagrotaGabriel/Loan-Management-cfg.git
          search-paths:
            - 'ms-service*'
